eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
  client:
    fetchRegistry: true
---
spring:
  profiles: local
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry1
  client:
    serviceUrl:
      defaultZone: http://service-registry2:8762/eureka/

---
spring:
  profiles: local1
    
server:
  port: 8762
  
eureka:
  instance:
    hostname: service-registry2
  client:
    serviceUrl:
      defaultZone: http://service-registry1:8761/eureka/
---
spring:
  profiles: docker
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry1
  client:
    serviceUrl:
      defaultZone: http://service-registry2:8761/eureka/

---
spring:
  profiles: docker1
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry2
  client:
    serviceUrl:
      defaultZone: http://service-registry1:8761/eureka/
      
---
spring:
  profiles: ecs
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry1-279569743.ap-southeast-1.elb.amazonaws.com
  client:
    serviceUrl:
      defaultZone: http://service-registry2-2082862406.ap-southeast-1.elb.amazonaws.com:8762/eureka/

---
spring:
  profiles: ecs1
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry2-2082862406.ap-southeast-1.elb.amazonaws.com
  client:
    serviceUrl:
      defaultZone: http://service-registry1-279569743.ap-southeast-1.elb.amazonaws.com:8761/eureka/
      