feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000

---
spring:
  profiles: local, docker
    
server:
  port: 8282
  
service-provider:
  url: http://localhost:8181
 
---
spring:
  profiles: ecs
    
server:
  port: 8282
  
service-provider:
  url: http://service-provider-923530181.ap-southeast-1.elb.amazonaws.com:8181
 
