server:
  port: 8888
 
management:
  endpoints:
    web.exposure.include=*

---
spring:
  profiles: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/

---
spring:
  profiles: docker
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
